### ISSUE TITLE
Update for xposed nougat by purifyos.

### ISSUE THREAD

**Issue by pabloa2** [Ashish-Bansal/OneTapVideoDownload#58]
Please update module to work with xposed api 25.

https://forum.xda-developers.com/xposed/xposed-android-nougat-sdk-25-arm64-t3639221/page1

**Comment by Ashish-Bansal** [comment]
Well, when I saw this issue, you can't imagine my happiness because I didn't know Xposed got a release for Nougat. But after digging more about it, I came across this[0]. So, I don't really plan to support it unless unofficial project by @abforce gets matured.

[0] https://github.com/rovo89/Xposed/issues/230#issuecomment-316623920

**Comment by pabloa2** [comment]
Um....okay.
